###
POST http://localhost:8080/merchants
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="merchants.csv";
Content-Type: text/csv

< ./src/test/resources/csv/merchants.csv
--boundary--

###
POST http://localhost:8080/orders
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="order.csv";
Content-Type: text/csv

< ./src/test/resources/csv/orders.csv
--boundary--

###
GET http://localhost:8080/disbursements/by-year
Content-Type: application/json